version: 2

x-common-config: &common-config
  schedule:
    interval: "weekly"
  groups:
    security:
      applies-to: "security-updates"
      patterns:
        - "*"
  open-pull-requests-limit: 0

updates:
  - package-ecosystem: "npm"
    directory: "/"
    <<: *common-config
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    <<: *common-config
  - package-ecosystem: "npm"
    directory: "/apps/web"
    <<: *common-config
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    <<: *common-config
  - package-ecosystem: "npm"
    directory: "/packages/domain"
    <<: *common-config
  - package-ecosystem: "npm"
    directory: "/packages/firebase"
    <<: *common-config
  - package-ecosystem: "npm"
    directory: "/firebase/functions"
    <<: *common-config
  - package-ecosystem: "github-actions"
    directory: "/"
    <<: *common-config
